### ISSUE TITLE
Support EdDSA

### ISSUE THREAD

**Issue by EternalDeiwos** [EternalDeiwos/keyto#1]
As per anvilresearch/webcrypto#9

**Comment by panva** [comment]
+1 for EdDSA (ed25519 and ed448) support

**Comment by OR13** [comment]
Any update on this?

**Comment by OR13** [comment]
https://github.com/digitalbazaar/crypto-ld/blob/master/lib/Ed25519KeyPair.js#L128

Coming from PEM / DER seems the worst part...

**Comment by EternalDeiwos** [comment]
Just pushed `1.0.0` which has support for ed25519
